import{useState}from'react';import{Link}from'react-router-dom';import SEO from'../components/SEO';import{work,packs,demos}from'../data/siteData';
const wa=t=>`https://wa.me/256775224728?text=${encodeURIComponent(t)}`;
const caps=[['Get found','Business information, location and SEO.'],['Show what you offer','Products, services, prices, galleries and menus.'],['Receive enquiries','WhatsApp, phone, email and structured forms.'],['Take bookings','Appointments, reservations and customer details.'],['Receive orders','Selection, cart, quantities and order handoff.'],['Improve workflows','Data capture, confirmations, storage and automation.'],['Connect services','Payments, APIs, social feeds and integrations.']];
export default function Business(){const[a,setA]=useState({x:false,y:false,z:false});const rec=a.z?'Advanced':a.y?'Business':a.x?'Standard':'Starter';return <div className="business"><SEO title="Web & Systems Development Kampala | Solomantalgo" description="Professional business websites, booking, ordering and digital systems in Kampala, Uganda."/><header><Link className="logo" to="/"><b>S</b> SOLOMANTALGO</Link><nav><a href="#work">Work</a><a href="#solutions">Solutions</a><a href="#packages">Packages</a><a href="#process">Process</a><Link to="/developer">For Employers</Link><a className="button" href={wa('Hi Solomon, I would like to discuss a website or digital system.')}>Let's talk</a></nav></header><main>
<section className="hero"><div><small>WEB & SYSTEMS DEVELOPMENT · KAMPALA, UGANDA</small><h1>Websites and digital systems built around how your business actually works.</h1><p>Professional websites and practical digital solutions for salons, restaurants, pharmacies and growing businesses—from getting online to booking, ordering, customer workflows and integrations.</p><p className="actions"><a className="button" href="#work">See Real Client Work</a><a className="button outline" href="#packages">View Packages</a></p><div className="notes"><span>UGX pricing</span><span>Direct developer contact</span><span>2 months routine updates</span></div></div><aside><div className="browser">● ● ● <span>Real websites built for businesses</span></div><img src="/images/medical.png" alt="Jopeem Pharmacy website preview"/><div><em>REAL CLIENT</em><strong>Jopeem Pharmacy</strong><a href="https://jopeempharmacy.com">View live ↗</a></div></aside></section>
<section id="work"><small>PROOF BEFORE PROMISES</small><h2>Real websites built for businesses</h2><p className="lead">Open genuine client work before exploring concept demos.</p><div className="cards">{work.map(w=><article key={w.n}><img src={w.img} alt={`${w.n} website preview`} loading="lazy"/><div><em>REAL CLIENT</em><small>{w.i}</small><h3>{w.n}</h3><p>{w.d}</p><a href={w.u} target="_blank" rel="noreferrer">View Live Website ↗</a></div></article>)}</div></section>
<section className="shade" id="solutions"><small>PRACTICAL BUSINESS CAPABILITIES</small><h2>What can your website or system help your business do?</h2><div className="capabilities">{caps.map((c,i)=><article key={c[0]}><b>0{i+1}</b><h3>{c[0]}</h3><p>{c[1]}</p></article>)}</div></section>
<section id="packages"><small>CAPABILITY-BASED PRICING</small><h2>Choose the right starting point</h2><p className="lead">Every package includes responsive design and two months of routine content updates after deployment.</p><div className="prices">{packs.map(p=><article className={p.hot?'hot':''} key={p.n}>{p.hot&&<em>POPULAR</em>}<small>{p.s}</small><h3>{p.n}</h3><strong>{p.p}</strong><ul>{p.f.map(f=><li key={f}>✓ {f}</li>)}</ul><details><summary>See full package details</summary><p>Final scope is based on required functionality. Major extra features and integrations are quoted separately.</p></details><a className="button" href={wa(`Hi Solomon, I'm interested in the ${p.n} website package for my business.`)}>Discuss {p.n}</a></article>)}</div>
<div className="recommender"><div><small>QUICK GUIDANCE</small><h3>Which website solution fits my business?</h3><p>Tick what you need. This is guidance, not a final quotation.</p></div><div>{[['x','Customers select, order or submit structured bookings'],['y','Store customer data or run confirmations/workflows'],['z','Connect payments, APIs or third-party services']].map(q=><label key={q[0]}><input type="checkbox" onChange={e=>setA({...a,[q[0]]:e.target.checked})}/>{q[1]}</label>)}</div><aside><small>BEST STARTING POINT</small><b>{rec}</b><span>{packs.find(p=>p.n===rec).p}</span><a className="button" href={wa(`Hi Solomon, your guide suggested ${rec}. I'd like to discuss it.`)}>Discuss on WhatsApp</a></aside></div></section>
<section className="shade"><small>DEMO LIBRARY</small><h2>Explore website ideas by industry</h2><div className="demo-grid">{demos.map(d=><a href={d[2]} target="_blank" rel="noreferrer" key={d[0]}><em>DEMO CONCEPT</em><small>{d[1]}</small><h3>{d[0]}</h3><b>Open demo ↗</b></a>)}</div></section>
<section id="process"><small>STRAIGHTFORWARD PROCESS</small><h2>From your idea to a working solution</h2><ol className="process">{[['Tell me about your business','Clarify what customers or staff need to do.'],['Choose the right solution','Agree on package and scope.'],['First version is built','Simple sites can often have a first version in around two days; advanced systems depend on scope.'],['Review and adjustments','Review and refine agreed details.'],['Go live','Deploy and connect the domain as applicable.'],['Two months routine updates','Prices, existing text, images, hours and promotions are covered.']].map((x,i)=><li key={x[0]}><b>{i+1}</b><div><h3>{x[0]}</h3><p>{x[1]}</p></div></li>)}</ol></section>
<section className="support"><div><small>SUPPORT AFTER LAUNCH</small><h2>Two months of routine updates included.</h2><p>Routine updates cover prices, existing images/text, business information, opening hours, promotions and items in existing sections. New pages, redesigns, major features and integrations are quoted separately.</p></div><details><summary>Ongoing maintenance options</summary><p>Active — UGX 80,000/month<br/>Weekly — UGX 50,000/month<br/>Bi-weekly — UGX 35,000/month<br/>Monthly — UGX 25,000/month</p></details></section>
<section className="cta"><small>READY TO BUILD?</small><h2>Tell me what customers or staff should be able to do.</h2><p>I'll recommend a clear, practical solution.</p><a className="button" href={wa('Hi Solomon, I would like to tell you what my business needs.')}>Tell Me What You Need</a></section></main><footer><Link className="logo" to="/"><b>S</b> SOLOMANTALGO</Link><span>Web & systems development · Kampala, Uganda</span><Link to="/developer">Developer Portfolio</Link></footer></div>}
